# Generated by Django 5.0.1 on 2026-09-23 12:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='token_value',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
